### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by chatomud** [chatomud/chatomud#3]
when a player does not input anything for a long time, weird things happen. they lose the connection, but the mud thinks they are still there. causes a crash sometimes

/home/chatomud/chatomud/lib/cm_socket.rb:6:in `gets': Connection timed out @ io_fillbuf - fd:17  (Errno::ETIMEDOUT)
        from /home/chatomud/chatomud/lib/cm_socket.rb:6:in `rx'
        from /home/chatomud/chatomud/lib/controllers/entities/player_controller.rb:46:in `block in process'
        from /home/chatomud/chatomud/lib/controllers/entities/player_controller.rb:45:in `loop'
        from /home/chatomud/chatomud/lib/controllers/entities/player_controller.rb:45:in `process'

input = gets
rx_result, input = @socket.rx

**Comment by chatomud** [comment]
this has been fixed with
```
          player_socket.setsockopt(Socket::SOL_SOCKET, Socket::SO_KEEPALIVE, true)
          player_socket.setsockopt(Socket::SOL_TCP, Socket::TCP_KEEPIDLE, 2)
          player_socket.setsockopt(Socket::SOL_TCP, Socket::TCP_KEEPINTVL, 2)
          player_socket.setsockopt(Socket::SOL_TCP, Socket::TCP_KEEPCNT, 2)
```
it looks like over kill - it is adding a keepalive signal sent every one or two seconds. Works for now, though, till we decide to tweak the values to more sensible ones.
