### ISSUE TITLE
login invalid byte sequence

### ISSUE THREAD

**Issue by chatomud** [chatomud/chatomud#6]
/activesupport-5.1.1/lib/active_support/core_ext/object/blank.rb:120:in `match?': invalid byte sequence in UTF-8 (ArgumentError)
from /home/chatomud/chatomud/lib/mixins/players/login.rb:21:in `handle_username'

**Comment by chatomud** [comment]
fixed in:

https://github.com/chatomud/chatomud/commit/d95952f625b310eb182115be20a1c7ed0960c1b1

according to:

https://robots.thoughtbot.com/fight-back-utf-8-invalid-byte-sequences
